### ISSUE TITLE
Parallel graph filtering

### ISSUE THREAD

**Issue by atilaajones** [GraphFilter/GraphFilter#112]
Currently, the software filter graphs using one single thread, which is time consuming, specially thinking about cases with many graphs and many conditions to be evaluated. The goal is to divide the filter into different threads to accelerate the process, enhancing the software.

1. Create simplified scenario:
      - First Window
      - Loading Window
      - Main Window

- [x] The First window should make some calculations using parallelism, and the loading window must update without crashing. When the process finishes, the main window should open.

2. Refactor Graph Filtering:

- [x] Modulate function
- [x] Implement multiprocessing on filtering
- [x] #178
- [x] Optimize the number of cores
- [x] Progress bar loads properly

Learn more:
- [Video](https://www.youtube.com/watch?v=EGJipyZBjbU)
- [Multiprocessing X Threads](https://www.ti-enxame.com/pt/python/multiprocessamento-vs-threading-python/969791624/)
- [Real Python - QThread](https://realpython.com/python-pyqt-qthread/)

**Comment by LBeghini** [comment]
One possibility is to define metrics to each algorithm and later make a weighted average and choose if the program should use multiprocessing.

**Comment by atilaajones** [comment]
It seems that it is necessary to use QThread when a PyQt runs a long task, to avoid window freezing.

The initial scheme would be:
- app runs on main thread;
- filtering runs on a secondary thread
- This thread creates several processes to perform filtering, using multiprocessing.
- Will the progress bar be updated from Qthread and multithreads?

[Link to PyQt and QThread](https://realpython.com/python-pyqt-qthread/)

**Comment by atilaajones** [comment]
**About the need to use multiprocessing in a filter:**
I noticed that to create 4 process it only takes 2sec, so there is no need for such specific measures. If filtering is expected to take more than 60s then it is better to use 4 or more processes.

**About the number of process**
It is interesting that the user has speed in their filtering process using multiprocess, but we cannot make the OS unusable, so the number of processes was defined as 1/3 of the total number CPU.

**The filter and loading**
The filter is working fine with multiprocess. But when use progress bar with real-time update, the program crashes. So need to implement progress bar.

**Comment by atilaajones** [comment]
When use the app to filter a list with multiprocess, the program stop and show the message on console:

![image](https://user-images.githubusercontent.com/41593241/134072932-33b733a0-38ac-42c5-b62e-ea029c00d703.png)

**Comment by atilaajones** [comment]
**NEWS: About the need to use multiprocessing in a filter:**
After meeting with @LBeghini, we were decided that the use of multiprocess will be defined as follows:
_Filtering starts normally, if it exceeds the time of 5 seconds, then it creates the multiprocesses and continues the filtering in multiprocess, where it left off._

**Comment by LBeghini** [comment]
Check [this site](https://realpython.com/python-pyqt-qthread/) to see an implementation of thread in PyQt.

**Comment by LBeghini** [comment]
To retake this task, it is valuable to make a simple case scenario, whit a Wizard Window calling some threads (to mock the parallel filtering) so we can fix the problem of the loading screen that crashes.

**Comment by atilaajones** [comment]
@fsoupimenta 
Current situation: build a minimal program to execute the progress bar [(by qthread)](https://doc.qt.io/qtforpython/PySide6/QtCore/QThread.html?highlight=qthread#more) while parallel tasks are executed [(by multiprocessing)](https://docs.python.org/3/library/multiprocessing.html), in the background. The progress of such tasks should update the progress bar.

This could be the reason for the freeze that occurred during execution.
