### ISSUE TITLE
 problem of matching number of graph

### ISSUE THREAD

**Issue by lichengzhang1** [GraphFilter/GraphFilter#116]
Unfortunately, in my computer (Windows 10), the matching number of graphs is invalid as the filtering condition.

![image](https://user-images.githubusercontent.com/82444903/130309080-8be9bf90-41e9-43ef-89db-9f7fd9135ea8.png)

**Comment by twahz** [comment]
I have the same problem！

**Comment by lichengzhang1** [comment]
> I have the same problem！
The problem does not seem to have been solved.

**Comment by atilaajones** [comment]
Hello.
In fact there is this bug. We will soon publish a repaired version.

Thank you very much for your collaboration and sorry for the delay to return.

**Comment by atilaajones** [comment]
Hello
We identified the bug that occurred. But we found that this bug does not occur in the source code, only in the executable. Let's work on the resolution and new release.
Regards.

**Comment by LBeghini** [comment]
I changed the `validate_expression`  on the *equation.py*  file, for when an Exception is found, log the error. Then, I generate an executable with PyInstaller on Windows, generating a spec file configured to show console and debug mode:
```spec
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None

a = Analysis(['app.py'],
             pathex=['D:\\Documentos\\GitHub\\GraphFilter.py'],
             binaries=[],
             datas=[('.\\resources\\data', 'resources\\data'), ('.\\resources\\icons', 'resources\\icons')],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='GraphFilter',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='resources\\icons\\hexagon.ico')
```

When executing the program, I got the following error:

```bash
unexpected EOF while parsing (<unknown>, line 1)
'NoneType' object has no attribute 'actualSolve'
```
I searched the problem and I found [this question on StackOverflow](https://stackoverflow.com/questions/60926887/py-project-works-but-pyinstaller-gives-error-related-to-pulp) that said that PyInstaller does not include extra packages necessary for pulp library to work. 

I managed to solve the problem by changing the spec file to:
```spec
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None

def get_pulp_path():
    import pulp
    return pulp.__path__[0]

a = Analysis(['app.py'],
             pathex=['D:\\Documentos\\GitHub\\GraphFilter.py'],
             binaries=[],
             datas=[('.\\resources\\data', 'resources\\data'), ('.\\resources\\icons', 'resources\\icons')],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

a.datas += Tree(get_pulp_path(), prefix='pulp', excludes=["*.pyc"])

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='GraphFilter',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='resources\\icons\\hexagon.ico')
```
I'll generate the executables and test both for Linux and Mac, and after that I'll launch a new release.

**Comment by LBeghini** [comment]
Now I am facing a problem that I cannot disable the console for the application. If i generate the spec file with the console option equals false, the error returns.

```python
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

def get_pulp_path():
    import pulp
    return pulp.__path__[0]

a = Analysis(['app.py'],
             pathex=['D:\\Documentos\\GitHub\\GraphFilter.py'],
             binaries=[],
             datas=[('.\\resources\\data', 'resources\\data'), ('.\\resources\\icons', 'resources\\icons')],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

a.datas += Tree(get_pulp_path(), prefix='pulp', excludes=["*.pyc"])

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='GraphFilter-2.0.1-win',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='resources\\icons\\hexagon.ico')
```

I [asked a question on StackOverflow](https://stackoverflow.com/questions/69868023/pulp-error-occurs-on-executable-when-running-pyinstaller-with-console-option-fal) describing the situation.

**Comment by LBeghini** [comment]
After the issue was solved, I was able to generate the Windows executable and it works properly.

However, after trying to generate it on MacOS system, I got the same error as before. I [described the error in PyInstaller](https://github.com/pyinstaller/pyinstaller/issues/6427), but I am still not able to find a way to properly fix the problem.

**Comment by LBeghini** [comment]
Following the suggestion I got from the issue open at PyInstaller, I opened an issue at PuLP to see if they can fix the problem so its not necessary to patch the library ourselves.

**Comment by LBeghini** [comment]
On windows. used the following command to run the installer:
```bash
pyinstaller --icon .\resources\icons\hexagon.ico --add-data ".\resources\data;resources\data" --add-data ".\resources\icons;r
esources\icons" --clean --noconfirm --collect-data pulp --name GraphFilter --onefile --noconsole app.py
```

And matching number is working, with some delay.

**Comment by LBeghini** [comment]
I tried the same above configuration on Linux, however I as getting the same error as before:

I managed to work around that by creating a spec file with the following:

```bash
pyi-makespec --icon ./resources/icons/hexagon.png --add-data "./resources/data:resources/data" --add-data "./resources/icons:resources/icons" --collect-data pulp --name GraphFilter --onefile --noconsole app.py 
```
Then, add to the file, after the creation of the `a` variable:

```spec
def get_pulp_path():
    import pulp
    return pulp.__path__[0]

a.datas += Tree(get_pulp_path(), prefix='pulp', excludes=["*.pyc"])
```
Generating the dist with this works perfectly.
Maybe I should add this as a note on PyInstaller.

**Comment by LBeghini** [comment]
It turns out the issue was Pulp wasn't updated on the Linux environment. The full description of the problem is described [here](https://github.com/pyinstaller/pyinstaller/issues/6567)
