### ISSUE TITLE
Bug with permission on C: Windows

### ISSUE THREAD

**Issue by atilaajones** [GraphFilter/GraphFilter#123]
If install and execute GraphFilter on Windows 10 and default local (C:/Program Files (x86)), when you try filter a list the progress bar stop on 99% and the console show the error:
_PermissionError: [Errno 13] Permission denied: 'C:/Program Files (x86)/Graph Filter/TEST.json'_

If you close the progress bar, so the app continues normally.

**Comment by LBeghini** [comment]
As Graph Filter does not have an installer anymore, this issue is outdated.
