### ISSUE TITLE
MacOS layout is broken

### ISSUE THREAD

**Issue by LBeghini** [GraphFilter/GraphFilter#153]
At the latest release it was noticed that the layout of the Wizard Window for MacOS systems are broken. It is necessary to find a way to fix it that does not break the other systems layouts too.

**Comment by LBeghini** [comment]
Here is an example of the behavior, it mainly happens at Wizard:
- Information
![image](https://user-images.githubusercontent.com/37659479/195186900-72f47e18-4ba8-4e50-b6d4-a3b614b91231.png)

- Review
![image](https://user-images.githubusercontent.com/37659479/195186989-053ffcf9-48e5-4b95-b140-2c563be4b7a5.png)

> **Note**  
> What happens is that the elements of the page are gathered in the middle

**Comment by rosaigor138** [comment]
The problem was that the Form Layout visualization for Mac is different than Windows, as we can see [here](https://doc.qt.io/qt-5/qformlayout.html#details).


However, we found a few errors not related  to our issue:
- The Review wizard page is not properly showing the labels
```shell
QWidget::setLayout: Attempting to set QLayout "" on ReviewPage "", which already has a layout
```
- Mac does not have the math font 
```shell
qt.qpa.fonts: Populating font family aliases took 3076 ms. Replace uses of missing font family "Cambria Math" with one that exists to avoid this cost. 
```

We will try to fix the conditions error, but we believe the font one belongs to another issue.

**Comment by LBeghini** [comment]
Also, it is necessary to figure it out how to minimize the Wizard.

**Comment by fsoupimenta** [comment]
When i changed the FieldGrowthPolicy from ExpandingFieldsGrow to AllNonFixedFieldsGrow, both the label problem and the conditions update were adjusted.
  - Proof

![Captura de Tela 2022-11-29 às 18 41 58](https://user-images.githubusercontent.com/108306295/204655038-278b853a-f622-42d4-89f0-e2125559e121.png)

**Comment by fsoupimenta** [comment]
Working in the issue, it was noticed that when a condition is deselected, she is not updated on the review page.
  - Here is an example
  - 
![New Project 2022-11-30 18-12-37](https://user-images.githubusercontent.com/108306295/204909999-ef2bf897-7989-41c0-93f1-f94ed8c45f67.gif)
