### ISSUE TITLE
Bug behavior Search Bar Invariants Dock 

### ISSUE THREAD

**Issue by LBeghini** [GraphFilter/GraphFilter#155]
The search bar sometimes do not scale with the project window. Investigate the reason why it happens and implement a fix.

Also, the scroll bar does not follow the research. A implementation of a policy to move it at the top when searching is needed.

> It is probably something with the scaling policy

**Comment by atilaajones** [comment]
The QlineEdit searchbar remains **fixed size**, without accompanying the dock. I still haven't been able to determine where specifically it has to change, but it seems that the function that will help is given by [QWidget.setSizePolicy()](https://doc.qt.io/qtforpython/PySide6/QtWidgets/QWidget.html?highlight=setsizepolicy#PySide6.QtWidgets.PySide6.QtWidgets.QWidget.setSizePolicy)

**Comment by LBeghini** [comment]
Maybe you should implement a smaller program to test this behavior? With just a window and a dock...  Maybe that would help to determine weather to change.
