### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by LBeghini** [GraphFilter/GraphFilter#156]
The README is outdated. Record the new layout screens and add the new functionalities.

**Comment by atilaajones** [comment]
@LBeghini 
Review the text to see if it needs any new changes for version 2.2.1.

This should be the last one issue to close, for the 2.2.1 release.

**Comment by LBeghini** [comment]
@atilaajones the [project window image](https://github.com/GraphFilter/GraphFilter/blob/main/resources/gifs/project_window.gif) have to be updated with the latest interface improvements we made. Maybe is for the better that we wait to finish the milestone to avoid rework in this manner.

**Comment by atilaajones** [comment]
Updates needed:

- [ ] Update images and gifs
- [ ] Cite the functionality of drawing graphs
- [ ] Highlight the accepted file formats: g6, txt (graph 6) and .gml
- [ ] Cite the tree file management.

**Comment by fsoupimenta** [comment]
> Updates needed:
> 
> * [ ]  Update images and gifs
> * [ ]  Cite the functionality of drawing graphs
> * [ ]  Highlight the accepted file formats: g6, txt (graph 6) and .gml
> * [ ]  Cite the tree file management.

The first topic you mentioned will be done in #378, to update the images used in the README and Wiki.
