### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by LBeghini** [GraphFilter/GraphFilter#157]
Update Wiki with version 3 features

**Comment by atilaajones** [comment]
@LBeghini 
Review the text to see if it needs any new changes for version 2.2.1.

This should be the last one issue to close, for the 2.2.1 release.

**Comment by fsoupimenta** [comment]
When generating the executable for [Windows](https://github.com/GraphFilter/GraphFilter/wiki/Windows-Configurations), i noticed that the command for bulding is outdated.
The directory no longer exists:
`--add-data ".\resources\data;resources\data"`

When i removed it, the script worked fine.

**Comment by fsoupimenta** [comment]
@LBeghini 
It also necessary add in [Linux Configurations](https://github.com/GraphFilter/GraphFilter/wiki/Linux-Configurations) the following code in the executing part:
```
sudo apt-get install libxcb-xinerama0
```
and 
```
./GraphFilter-x.x.x-linux
```
> Replace x.x.x for the version number of the release

**Comment by atilaajones** [comment]
The issue description has been updated, for a refactoring of the wiki.

**Comment by atilaajones** [comment]
The Wiki has been updated to version 3.0, according to the topics listed in the previous post. A refactoring of the Wiki has been proposed for a new issue #434
