### ISSUE TITLE
Can GraphFilter add some graph's generators (for example, geng)

### ISSUE THREAD

**Issue by lichengzhang1** [GraphFilter/GraphFilter#158]
At the moment, it looks like _GraphFilter_ can only be used to filter graphs that are already in the user's database.
So if  GraphFilter  has some generators of graphs built in, it will enrich the function of the software.

Some popular graph generators are as follows:

> [geng](https://users.cecs.anu.edu.au/~bdm/nauty/); the program _geng_ can generate all unlabelled simple graphs on a given number of vertices with various additional properties. , which is  part of nauty, written by Brendan McKay.

> [plantri and fullgen](https://users.cecs.anu.edu.au/~bdm/plantri/); _plantri_ and _fullgen_ are programs for generation of certain types of planar graph.

**Comment by atilaajones** [comment]
Hello @lichengzhang1

Thank you very much for your interest in the Graph Filter software.

In fact, the software is used for filtering graphs. In [House of Graphs](https://hog.grinvin.org/MetaDirectory.action) there is a database of graphs (already generated) separated into some classes. The software also has a button for this page

If the user wants to generate graphs with various additional properties (like [geng](https://users.cecs.anu.edu.au/~bdm/nauty/)), this can also be done through the filtering available in the Graph Filter, using simple graphs as input, already available [here](http://users.cecs.anu.edu.au/~bdm/data/graphs.html).

Anyway, let's also consider your idea of maybe incorporating a graph generator into the software itself.

Thanks again!!
