### ISSUE TITLE
The graphs cannot be editable

### ISSUE THREAD

**Issue by atilaajones** [GraphFilter/GraphFilter#163]
The graph drawing package (netgraph #137) allows graphs to be editable (with insertion and removal), however the invariants should be updated in real time.

So editing should be blocked for now, until an issue is made that makes this update.

- [ ] Change iteration with graphs to non-editable mode (only moving vertices) in visualization window.

**Comment by atilaajones** [comment]
I understand, there's really no need to solve it now. But we cannot publish a version with this vertex and edge insert/remove permission.

**Comment by LBeghini** [comment]
I mean, it is like an easter egg. We do not at any moment even mention that is possible to add vertex or arrows, not how it works., so it would hardly be a problem. 

One possibility is to let the owner of netgraph know about this problem. 
Or  we can decide to only publish another version once we finish with the drawing part.
