### ISSUE TITLE
Change default folder

### ISSUE THREAD

**Issue by atilaajones** [GraphFilter/GraphFilter#166]
When creating a new filter, on the first wizard page, the default location where the software will be saved points to a random location on the executable.

That should be fixed so it points to Documents folder por example.

**Comment by rosaigor138** [comment]
In the last commit I changed the default folder in the label and disabled the possibility of the user change manualy the value. But during the bug solving I encountered another issue, when the button to open folder is clicked he do not have any association with the label, he open in the local where the code is found. 

That bug can be a problem when the code becomes a executable, to solve that we need a new way to open the folder, now previously vinculated to some directory.

**Comment by LBeghini** [comment]
@rosaigor138 I found [this answer at StackOverflow](https://stackoverflow.com/questions/65410612/pyqt5-file-dialog-the-last-opened-file-becomes-the-initial-path-for-the-next-u). You might want to take a loot.
Basically it states a way to pass a file path to `QFileDialog`

```python
self.Filename = QFileDialog.getOpenFileName(directory=self.path.text())
```
