### ISSUE TITLE
Fix minimization error

### ISSUE THREAD

**Issue by LBeghini** [GraphFilter/GraphFilter#205]
The minimization is added early and worked pretty well on windows, but when we come back to macOS we found a problem that the window do not minimize.

**Comment by LBeghini** [comment]
@rosaigor138 can you please add the description?

**Comment by rosaigor138** [comment]
The minimization is added early and worked pretty well on windows, but when we come back to macOS we found a problem that the window do not minimize.
-More about the problem: When we try to minimize the window it enable an bugged maximize button.

-Resolving the problem: I changed the flags to custom, that way the only flags enabled is the one's I choose.

**Comment by rosaigor138** [comment]
-More about the problem: When we try to minimize the window it enable an bugged maximize button, probably because of already stablished flags.

-Resolving the problem: I changed the flags to custom, that way the only flags enabled is the one's I choose.
