### ISSUE TITLE
Refactor box layout on equations_page

### ISSUE THREAD

**Issue by fsoupimenta** [GraphFilter/GraphFilter#213]
Opening the software on a Linux virtual machine at a resolution lower than 800x600, it was noticed that the box in equations page is so small that it is not possible to read.

So, it's necessary to add an scroll bar in the box and reduce the number of columns in it.

Here is an example of the behavior

  - Equation
![Screenshot_14](https://user-images.githubusercontent.com/108306295/207733184-a6840017-d1be-46f4-a3dc-1f6636661b5d.png)

**Comment by atilaajones** [comment]
Currently, something similar is also happening at high resolutions, due to the amount of spectral invariants. So it is necessary to separate this tab into two new ones: "Spectral Invariants [1]" and "Spectral Invariants [2]".

**Comment by atilaajones** [comment]
Can you reproduce this error again? Because the already menu was separated into two tabs.
