### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by atilaajones** [GraphFilter/GraphFilter#238]
The transparency effect has errors when we make editing sequences. What I propose is to remove this visual effect of transparency when hovering over vertices and edges.

![image](https://user-images.githubusercontent.com/41593241/217919439-20bee4e8-bd79-4928-a300-99f6a2d1ff16.png)

**Comment by fsoupimenta** [comment]
@atilaajones, 
I found the reason behind this bug, but i believe that we can't solve/it's hard to solve it.
So, i suggest open an issue on netgraph

**Comment by fsoupimenta** [comment]
This issue was resolved by netgraph [here](https://github.com/paulbrodersen/netgraph/issues/66).

So, we just have to update the requirements
