### ISSUE TITLE
Smallest eigenvalue of a matrix associated with a graph

### ISSUE THREAD

**Issue by CybeleVinagre** [GraphFilter/GraphFilter#273]
Could you please implement the calculation of the spread of eigenvalues of a Hermitian  matrix associated to a graph? Please, find the definitions and details in attachment.
Thanks in advance.
Best regards

[Art Gregory Kirkland et al. The spread of the spectrum of a graph (1).pdf](https://github.com/GraphFilter/GraphFilter/files/11245551/Art.Gregory.Kirkland.et.al.The.spread.of.the.spectrum.of.a.graph.1.pdf)

**Comment by atilaajones** [comment]
Hello. @CybeleVinagre 

Thank you very much for your interest and contribution in our software.
It is an invariant that can be implemented, currently developing the 3.0 version, so this demand will be launched together with this new version.

**Comment by atilaajones** [comment]
@fsoupimenta 
The **Spread of the spectrum** invariant must be available in equation inputs and in the project window. Similar to the other energies already implemented. This invariant must be avaible on filtering (equation) and project window, like the others numeric invariants.
