### ISSUE TITLE
Eccentricity invariants of a graph

### ISSUE THREAD

**Issue by CybeleVinagre** [GraphFilter/GraphFilter#274]
Could you please implement the calculation of the eccentricity energy of a graph?
Thanks in advance.

**Comment by atilaajones** [comment]
Hello. @CybeleVinagre 

Thank you very much for your interest and contribution in our software.
It is an invariant that can be implemented, currently developing the 3.0 version, so this demand will be launched together with this new version.

**Comment by atilaajones** [comment]
@fsoupimenta 
The **Eccentricity energy** invariant must be available in equation inputs and in the project window. Similar to the other energies already implemented.
