### ISSUE TITLE
Update 'numpy' in requirements

### ISSUE THREAD

**Issue by Viech** [GraphFilter/GraphFilter#330]
This feature was [deprecated as of NumPy 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) and [removed in version 1.24](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations).

The following is printed to the console when an expression is created:

> module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

The UI simply says `Invalid Equation: Unknown items in the expression`. So, additionally, the exception handling seems to be inaccurate as it reports an unrelated exception as a user syntax error.

**Comment by atilaajones** [comment]
Hello @Viech, thank for report.

Could you give an example of the situation that reproduced this error, so that we can better understand? You can do image uploads if you prefer.

**Comment by Viech** [comment]
1. `New Project`
2. `Filter Graphs`
3. `Next`
4. enter a project name
5. `Next`
6. enter any valid expression, say `n(G) == 1`
7. the console and UI behave as described above; the `Next` button is disabled

**Comment by atilaajones** [comment]
You are running the application from .exe on WIndows ?

I tested it here and didn't get the problem (see below)
![image](https://github.com/GraphFilter/GraphFilter/assets/41593241/2b745fde-5145-4f88-ab3b-11c98925c047)

**Comment by Viech** [comment]
If this works for you, then you are likely using a NumPy version older than 1.24.

The issue seems to be that GraphFilter uses `numpy.bool`:

```
% grep -r numpy.bool
source/domain/equation.py:        return type_ex == numpy.bool or type_ex == numpy.bool_ or type_ex == bool
```

Use of `numpy.bool` was deprecated as of NumPy 1.20, and raises an exception in NumPy 1.24 or later. So `type_ex == numpy.bool` will not evaluate to `True` or `False` any more, but raise an `AttributeError`. Please see my first post for more information on that.

**Comment by atilaajones** [comment]
Yes, we understand what you are saying. We then observe that you are using the source version, not the release version.

- If you use the [release version](https://github.com/GraphFilter/GraphFilter/releases), there is no problem.

- But if you prefer to use source, then you must follow [requirements.txt](https://github.com/GraphFilter/GraphFilter/blob/main/requirements.txt) exactly for the software to work properly [(see here)](https://github.com/GraphFilter/GraphFilter/wiki/General-Configurations#required-libraries). The requirements are updated according to the software development

Anyway, we will soon publish version 3.0 of Graph Filter, where all these libraries will be updated (including numpy). 

Any questions or suggestions, we remain at your disposal. Thank you.

**Comment by atilaajones** [comment]
I updated **_numpy_** to 1.24.3. However, even though `numpy.bool` and `numpy.bool_` are out of use, the [simpleeval](https://github.com/danthedeckie/simpleeval) library is still using them (even in its latest version). So we need the comparations implemented:

> return type_ex == numpy.bool_ or type_ex == bool

@Viech, this does not interfere with the working of the _**Graph Filter**_, as long as you use (rigorously) the versions imposed in [requirements.txt](https://github.com/GraphFilter/GraphFilter/blob/main/requirements.txt).
