### ISSUE TITLE
Progress bar cancels the process

### ISSUE THREAD

**Issue by atilaajones** [GraphFilter/GraphFilter#339]
If you close the progress bar, the process must be canceled. This functionality must be implemented:

- [x] For filtering: the filtering is canceled and the program is closed.
- [ ] Export all: the process is canceled and the project_window continues as it was (optional)

Suggestion: insert Cancel button and remove close button.

**Comment by rosaigor138** [comment]
I don't know if it is possible to stop the execution of just one method through an event in another class, in this case the export method.
