### ISSUE TITLE
Bug when opening a gml graph in the tree

### ISSUE THREAD

**Issue by fsoupimenta** [GraphFilter/GraphFilter#348]
If you try to open a gml file without node positions in tree, the software crashes. 
This happens because it is trying to use the previous dictionary positions in the new graph.

To reproduce the error:

1. Open any graph
2. Open a gml graph without node positions from the tree

**Comment by rosaigor138** [comment]
Ah, this problem occurred when I was doing the corrections for #340, but I couldn't figure out when it occurred, so I put my PR in draft

**Comment by atilaajones** [comment]
What do you mean opening a gml without node position?
