### ISSUE TITLE
Mac problems pre-release

### ISSUE THREAD

**Issue by atilaajones** [GraphFilter/GraphFilter#377]
When performing the 3.0 pre-release there were problems observed in the MAC.

- [x] When double-clicking a folder in the tree the program start a infinite loop. Observe the return of the folder double click on the MAC.
- [x] When changing the project creation location, the NEXT button is blocked. The problem is that the character `\` is forbidden.
- [x] Create new shortcut keys for vertex editing: The `=` should insert vertex, the `bacskpace` should remove.
- [x] Test if it is easy to implement insertion using `SHIF + mouse click`.
- [ ] When navigating the combobox, the view dock is squeezed, check behavior and min/max dock sizes.
- [x] After performing a filter the .g6 file is being saved in one location and the tree opening in another, this prevents editing the file. It seems to be a translation problem.

**Comment by fsoupimenta** [comment]
@atilaajones  

After analyzing the netgraph code, it seems to me that it is not trivial to implement ```SHIFT + Left Click```, because they are different events that have their own method, such as `on_key_press` and `on_press`.

**Comment by atilaajones** [comment]
> @atilaajones
> 
> After analyzing the netgraph code, it seems to me that it is not trivial to implement `SHIFT + Left Click`, because they are different events that have their own method, such as `on_key_press` and `on_press`.

Correct. So for this issue we will make only the remaining changes

**Comment by atilaajones** [comment]
@rosaigor138 
To solve problems with resizing docks and plotting graphs. Perform the tests:

- The dock of the view dock with a fixed size.
- The software window always in full-screen.
