### ISSUE TITLE
Implementation new spectral invariants

### ISSUE THREAD

**Issue by CybeleVinagre** [GraphFilter/GraphFilter#385]
Describe in detail what you would like to suggest for the software:

 
 I suggest the inclusion of some invariants and matrices:
Randic index (see the file in attachment -  it has a relationship with the Randic Matrix, but is has been defined before that);
Randic Matrix and Randic energy;
Note 1: Please,  pay attention to the relationship between Randic Matrix and Laplacian Matrix for graphs without isolated vertices;

 Degree Kirchhoff's index (see Haiyan Chen and Fuji Zhang. Resistance distance and the normalized Laplacian
spectrum. Discrete Applied Mathematics, 155(5):654{661, 2007.)

Kemeny's constant (see Steve Butler. Algebraic aspects of the normalized Laplacian. In Recent Trends in
Combinatorics, pages 295{315. Springer, 2016.)
...

**Comment by atilaajones** [comment]
@CybeleVinagre 
Hello, excellent invariant suggestions. The following invariants have been implemented:

- Kirchhoff Index
- Degree Kirchhoff's index
- Randic Matrix (spectrum, matrix, eigenvector, energy, ...)
- Randic Index.

All these invariants will be available in the next published version. 
Thank you for your interest in our project
