### ISSUE TITLE
Graph plotting problem

### ISSUE THREAD

**Issue by rosaigor138** [GraphFilter/GraphFilter#394]
A graph with saved positions changes every time the file is changed and becomes "smaller and smaller".

**To Reproduce**
1. Open one .gml archive and add one Node
2. Save and change the file
3. Go back to the original File
4. Repeat the proccess and you see the graph become smaller

**Screenshots**

![graphPrint01](https://github.com/GraphFilter/GraphFilter/assets/93498324/580523df-69c7-4194-b524-c421592bec1d)
![graphPrint02](https://github.com/GraphFilter/GraphFilter/assets/93498324/1e4d53bd-b80b-4ee6-bbd6-4582bf4efc6c)
![GraphPrint03](https://github.com/GraphFilter/GraphFilter/assets/93498324/0e854c35-faf4-40e6-a5a9-0b65c6ff2018)

**Additional context**
This problem seems to occur when saving and plotting the positions of vertex

**Comment by fsoupimenta** [comment]
this issue has to do with #374
