### ISSUE TITLE
Gif not loading on README

### ISSUE THREAD

**Issue by LBeghini** [GraphFilter/GraphFilter#400]
The gif images are not loading on [README.md](https://github.com/GraphFilter/GraphFilter/blob/main/README.md). 

That is because all gifs are surrounded by an `h4` HTML tag, that should be replaced by a `p` tag.

### Example

```diff
- <h4 align="center">
+ <p align="center">
<image src="/resources/gifs/project_toolbar.gif" width="800">
- </h4>
+ </p>
```

**Comment by atilaajones** [comment]
Please also update the links to the wiki. Some have broken after changes were made.
