### ISSUE TITLE
Find all extremal graphs in input graphs

### ISSUE THREAD

**Issue by lichengzhang1** [GraphFilter/GraphFilter#410]
Right now, the software can only filter based on graph properties, but it doesn't allow for comparing something between them. For instance, if I want to pick graphs with maximum dominating number from a group of graphs, which is a common task in extremal graph theory, it would be great to have that feature. Perhaps should consider adding a "Max" or "Min" function.

This feature is somewhat similar to what I mentioned before; see [https://github.com/GraphFilter/GraphFilter/issues/167](https://github.com/GraphFilter/GraphFilter/issues/167), but the problem here is a bit more commonly used.

**Comment by atilaajones** [comment]
@lichengzhang1 
Thank you for your interest in our software.

The search for extreme graphs is very important. But the filtering implemented in the software works by considering each graph individually, without comparison features. 

But the case of searching for extremal graphs is already possible in the newest version ([here](https://github.com/GraphFilter/GraphFilter/releases)) of the software, using the graph list export feature in an excel spreadsheet. Follow the steps below:

1. Download the file with the graphs you want to search for extremals. [House of Graphs](https://houseofgraphs.org/meta-directory) has graphs separated into classes, while [Brendan McKay](http://users.cecs.anu.edu.au/~bdm/data/graphs.html) has a file with all the graphs.
2. Run the software and open the file.
3. In the main window, select the invariant you want to maximize (e.g. **Domination Number**).
4. In the file tree, right-click on the file containing the graphs. Select "**Export all graphs to > Sheet**".
5. In the Excel file generated, you will see a list of all the graphs with the respective invariant calculated. Then simply sort the Excel column in order (ascending or non-descending) to see the extremum.
6. To visualize the graph, you can look at its id and navigate to the Graph Filter combo box. Or you can copy your g6 code and in the graph filter create a new graph (_button in the toolbar_) from a graph6 code.

If you need any help with this procedure, we're happy to help.

In any case, we would like to stress that we will consider your suggestions, as it is very useful to have filters that work with comparisons.
