### ISSUE TITLE
The first one for exporting all as PNG is quite strange.

### ISSUE THREAD

**Issue by lichengzhang1** [GraphFilter/GraphFilter#421]
**Describe the bug**
I have the following 10 graphs.

Windows 10 +3.1.2

```
H?AFvp{
J????A?~b~?
H?`vf`w
J???C@?~b}?
H?B@~rw
H?bfbro
J????B?N|}?
I??CBrw^_
I??CBzw]_
O?????????????_?W?B~}
```
When I exported all the graphs by using png-format (click `Export all graphs to...`), I see the first graph is shown in the following.

![image](https://github.com/GraphFilter/GraphFilter/assets/82444903/230142c0-25df-4158-91a6-a8c053a0ffeb)

The rest of the images are fine; I suspect the first one has become an overlay of all the images.

**Comment by fsoupimenta** [comment]
Hi, @lichengzhang1

I tried to reproduce the bug on my computer, but everything worked fine here.

Was this supposed to be the image of the first graph?
![Graph_1](https://github.com/GraphFilter/GraphFilter/assets/108306295/c4c5b044-ae54-4e0b-aedf-bdc36a48b700)

I believe this is a specific situation, so can you give me more information? Such as which version of the software, which operating system you are using and if it happens on every export?

Thank you in advance for your cooperation and for reporting this bug, it helps us a lot :)

**Comment by lichengzhang1** [comment]
Thank you.  I use  v 3.1.2 and windows 10.

**Comment by lichengzhang1** [comment]
I restarted the software, and now it is fine. So strange.

**Comment by lichengzhang1** [comment]
I restart the software, an now it is fine. So strange.
