### ISSUE TITLE
Refactor Graph Information Dock

### ISSUE THREAD

**Issue by LBeghini** [GraphFilter/GraphFilter#96]
- [x] Remove the verification that fixes the height
- [x] Set the table to fill the entire dock space
- [x] Set the dock features to Closable, Movable and Floatable

**Comment by LBeghini** [comment]
I don't know if it is a good solution to let the scroll bar visible when it's not possible to scroll the page. It's counter intuitive.

**Comment by atilaajones** [comment]
Now the column has a minimum initial size, if the content does not fit in this column, it will be expanded and the scroll bar will be displayed.  @LBeghini 
ok?

**Comment by LBeghini** [comment]
The scrollbar is always displayed. That's the problem.

**Comment by atilaajones** [comment]
No. I said before. I configured the scroll bar to appear when the text is larger than the dock

**Comment by LBeghini** [comment]
The scrollbar is always displayed. As soon as I open the project, it's already there.

**Comment by atilaajones** [comment]
Now it's ok. The commit was only local.

**Comment by LBeghini** [comment]
Its better but it still don't fill the entire info dock. 
![image](https://user-images.githubusercontent.com/37659479/118708325-f926c100-b7f1-11eb-8530-d8ad166c5251.png)

And the table does not resize with the dock
![image](https://user-images.githubusercontent.com/37659479/118708393-0e035480-b7f2-11eb-8ff6-56ffbcb84193.png)
